language: java
sudo: false
install: true
dist: trusty

addons:
  sonarcloud:
    organization: "gnafu"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=${sonar_projectKey}

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
